#ifndef STATUS_CODE_H
#define STATUS_CODE_H

#define STATUS_BEGIN_READ 1
#define STATUS_BEGIN_WRITE 2
#define STATUS_DATA_SEND 3
#define STATUS_DATA_RECEIVED 4
#define STATUS_DATA_RESEND 5
#define STATUS_ALL_DATA_SEND 6
#define STATUS_TRANSITION_CLOSED 7
#define STATUS_ALL_DATA_RECEIVED 8
#define STATUS_MANY_CONNECTION 9
#define STATUS_FILE_ALREADY_USED 10

#endif